version: 2
jobs:

   build:
    docker:
      - image: paulinhu/netcore-docker-build
    steps:
        - checkout
        - run: dotnet restore src
        - run: dotnet build src
        - run: dotnet publish src/fruit-preferences-api.csproj -c Release -f netcoreapp2.0
        - run: cp src/Dockerfile src/bin/Release/netcoreapp2.0/publish/
        - setup_remote_docker
        - run: docker build --rm --no-cache -t $DOCKER_IMAGE_NAME_WITH_REGISTRY src/bin/Release/netcoreapp2.0/publish/
        - run: docker login $DOCKER_REGISTRY_URI --username $DOCKER_REGISTRY_SERVER_USERNAME --password-stdin $DOCKER_REGISTRY_SERVER_PASSWORD
        - run: docker push $DOCKER_IMAGE_NAME_WITH_REGISTRY

workflows:
  version: 2
  build_and_test:
    jobs:
      - build