version: 2
jobs:

   build:
    docker:
      - image: paulinhu/netcore-docker-build
    steps:
        - run: dotnet restore 
        - run: dotnet build 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build