version: 2
jobs:

   build:
    docker:
      - image: paulinhu/netcore-docker-build
    steps:
        - checkout
        - run: dotnet restore src
        - run: dotnet build src
        - run: dotnet publish src/fruit-preferences-api.csproj -c Release -f netcoreapp2.0
        - run: cp src/Dockerfile src/bin/Release/netcoreapp2.0/publish/
        - setup_remote_docker
        - run: docker build --rm --no-cache -t $dockername src/bin/Release/netcoreapp2.0/publish/
        - run: echo "y" | docker login $DOCKER_REGISTRY_URI -u $DOCKER_REGISTRY_SERVER_USERNAME -p $DOCKER_REGISTRY_SERVER_PASSWORD
        - run: docker push $dockername

workflows:
  version: 2
  build_and_test:
    jobs:
      - build