version: 2
jobs:

  build_and_deploy:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - run: aws ecr get-login --no-include-email --region us-east-2
      - run: docker build -t fruitpreferences .
      - run: docker tag fruitpreferences:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fruitpreferences:latest
      - run: docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fruitpreferences:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy