version: 2
jobs:

   build:
    docker:
      - image: paulinhu/netcore-docker-build
    steps:
        - checkout
        - run: dotnet restore src
        - run: dotnet build src

workflows:
  version: 2
  build_and_test:
    jobs:
      - build