jobs:
    build_and_deploy:

        machine:
        services:
            - docker

        steps:
        - run: |
            - docker build -t fruitpreferences .
            - docker tag fruitpreferences:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fruitpreferences:latest
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fruitpreferences:latest
            - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/fruitpreferences .
            - docker run -d -p 8080:8080 --name sample-go-webapp $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/fruitpreferences; sleep 10
            - ./deploy.sh
    

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy
      - prod