workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy

    machine:
  services:
    - docker

dependencies:
  post:
    - docker build -t fruitpreferences .
    - docker tag fruitpreferences:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fruitpreferences:latest
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fruitpreferences:latest
    - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/go-sample-webapp:$CIRCLE_SHA1 .

test:
  post:
    - docker run -d -p 8080:8080 --name sample-go-webapp $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/go-sample-webapp:$CIRCLE_SHA1; sleep 10
    - curl --retry 10 --retry-delay 5 localhost:8080 | grep "Hello World!"

deployment:
  prod:
    branch: master
    commands:
      - ./deploy.sh